sudo: required
dist: trusty

services:
  - docker

install:
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - source env.sh
  - docker-compose up -d

script:
  - ./tests/test.sh

after_script:
  - docker-compose down