# Use container based Ubuntu 'trusty' distribution for faster boot time
# https://docs.travis-ci.com/user/reference/overview/
sudo: required
dist: trusty

services:
  - docker

install:
  - docker version
  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - source env.sh
  - docker-compose up -d

script:
  - ./test.sh

after_script:
  - docker-compose down