version: '3'
services:
  producer:
    build: ./producer
    command: /wait-for ${KAFKA_SERVER} -- python app.py
    volumes:
      - ./producer:/app
      - ./wait-for:/wait-for
    ports:
      - "5000:80"
    environment:
      KAFKA_SERVER: ${KAFKA_SERVER}
      KAFKA_TOPIC_1: ${KAFKA_TOPIC_1}
  consumer:
    build: ./consumer
    command: /wait-for ${KAFKA_SERVER} -- python app.py
    volumes:
      - ./consumer:/app
      - ./wait-for:/wait-for
    ports:
      - "5001:80"
    environment:
      KAFKA_SERVER: ${KAFKA_SERVER}
      KAFKA_TOPIC_1: ${KAFKA_TOPIC_1} 
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST} #ipconfig getifaddr en0
      KAFKA_CREATE_TOPICS: ${KAFKA_CREATE_TOPICS} #create 'foo' and 'bar' topics
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tests/kafka:/tests
      - ./wait-for:/wait-for