version: '3'
services:
  producer:
    build: ./producer
    # image: python
    command: /wait-for kafka:9092 -- python app.py
    # command: bash
    # stdin_open: true
    volumes:
      - ./producer:/app
      - ./wait-for:/wait-for
    ports:
      - "5000:80"
    environment:
      KAFKA_SERVER: kafka:9092
      KAFKA_TOPIC_1: foo
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST} #ipconfig getifaddr en0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tests/kafka:/tests
      - ./wait-for:/wait-for